# NUMPY - Multidimensional Data Arrays

It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. NumPy brings the computational power of languages like C and Fortran to Python, a language much easier to learn and use.

In [24]:
import numpy as np

In [3]:
np.__version__

'1.20.1'

In [26]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

## What is Array?

![](image/array.png)

In [5]:
# Python List

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [6]:
print(a+b)
print(a*b)

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: can't multiply sequence by non-int of type 'list'

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



In [7]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array / b_array)

[ 6  8 10 12]
[0.2        0.33333333 0.42857143 0.5       ]


## Creating `numpy` arrays

There are some ways to initialize new numpy arrays:
* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### Lists

In [8]:
# vector: the argument to the array function is a list
v = np.array([1, 2, 3, 4, 5])

v.shape

(5,)

In [9]:
# matrix: the argument to the array function is a nested list
m = np.array([[1, 2, 3], [4, 5, 6]])

m.shape

(2, 3)

The `v` and `m` objects are both of the type `ndarray` that the `numpy` module provides.

In [10]:
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

In [11]:
a = [1,2,3]

In [12]:
type(a)

list

The difference between the `v` and `m` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [13]:
v.shape

(5,)

In [14]:
m.shape

(2, 3)

The number of elements in the array is available through the `ndarray.size` property

In [15]:
m.size

6

`numpy.ndarray` looks very similiar to the `list`. So, why not use the list instead?
`numpay.ndarray` is used for several reason:
1. Lists are very general. They can contain any kind of object. They do not support mathematical functions such as matrix and dot multiplication, etc. 
2. Numpy arrays are statically typed and homogenous. The type of the elements is determined when the array is created
3. Numpy arrays are memory efficient
4. It is fast for implementation of mathematical function

We can see the type of data of an array using `dtype`

In [17]:
one_dimension = np.array([1, 2, 3])

two_dimension = np.array([[4, 5, 6],
                          [7, 8, 9]])

two_dimension



array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
Tugas:
membuat array 1 dimensi 7, 
membuat array 2 dimensi 3, 3
membuat array 3 dimensi 4, 4, 4

In [18]:
# Soal kedua

second_answer = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

# Print hasil
second_answer

# Shape
second_answer.shape

(3, 3)

In [19]:
# Soal ketiga
# Buatlah array 3 dimensi dg ashape 4, 4, 4

# answer
third_answer = np.array([[[1, 2, 3, 5],
                          [4, 5, 6, 6],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]],
                         
                         [[1, 2, 3, 8],
                          [4, 5, 6, 8],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]],
                         
                         [[1, 2, 3, 8],
                          [4, 5, 6, 8],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]],
                         
                         [[1, 2, 3, 8],
                          [4, 5, 6, 8],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]]])

# Print hasil
third_answer

# Shape
third_answer.shape

(4, 4, 4)

In [20]:
ones = np.ones((7, 7), dtype=int)

# Print ones
ones

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [41]:
m = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=float)

m

dtype('float64')

Common data types that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

### Create Matrix Zeros

In [ ]:
# One dimension

zeros_matrix = np.zeros(5)

zeros_matrix

In [ ]:
#two dimension

zeros_matrix2 = np.zeros(5,2)

In [ ]:
# should  be in tuple format

zeros_matrix2 = np.zeros((5,2)) # 5 rows, 2 columns
zeros_matrix2 

### Matrix ones

In [ ]:
#one dimension

matrix_ones = np.ones(5)
matrix_ones 

In [ ]:
#3 dimension

matrix_ones2 = np.ones((3, 4, 2)) #3 rows, 4 columns, 2 depth
matrix_ones2

## > Exercise 1

1. Create a matrix from a list which has 4 rows and 3 columns

In [27]:
m1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10,11,12]])
m1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
m1.shape

(4, 3)

2. Create the following matrix
![](image/lat11.png)

In [29]:
m2 = np.array([
                [2,7,12,0],
                [3,9,3,4],
                [4,0,1,3]
            ])
m2

array([[ 2,  7, 12,  0],
       [ 3,  9,  3,  4],
       [ 4,  0,  1,  3]])

3. Create a 2D matrix with size of 10

In [30]:
cara1 = np.array([
                 [1,2,3,4,5],
                 [6,7,8,9,10]
                ])
cara1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
cara2 = np.zeros((1,10))
cara2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
cara3 = np.array([[1,2],
                 [2,2],
                 [2,1],
                 [3,3],
                 [4,5]])
cara3

array([[1, 2],
       [2, 2],
       [2, 1],
       [3, 3],
       [4, 5]])

In [38]:
cara4 = np.array([[1],
                 [2],
                 [2],
                 [3],
                 [4],
                 [9],
                 [10],
                 [10],
                 [7],
                 [1]])
cara4

array([[ 1],
       [ 2],
       [ 2],
       [ 3],
       [ 4],
       [ 9],
       [10],
       [10],
       [ 7],
       [ 1]])

In [39]:
print("Size cara1: ", cara1.size)
print("Size cara2: ", cara2.size)
print("Size cara3: ", cara3.size)
print("Size cara4: ", cara4.size)

Size cara1:  10
Size cara2:  10
Size cara3:  10
Size cara4:  10


In [40]:
print("Shape cara1: ", cara1.shape)
print("Shape cara2: ", cara2.shape)
print("Shape cara3: ", cara3.shape)
print("Shape cara4: ", cara4.shape)

Shape cara1:  (2, 5)
Shape cara2:  (1, 10)
Shape cara3:  (5, 2)
Shape cara4:  (10, 1)


4. Create a 3D matrix of ones which has 2 rows, 3 columns, and 3 depth

In [42]:
m4 = np.array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[6, 2, 3],
        [4, 5, 8],
        [8, 8, 9]]])
m4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[6, 2, 3],
        [4, 5, 8],
        [8, 8, 9]]])

In [43]:
m4.shape

(2, 3, 3)

5. Make the following arrays from zeros arrays and with for loops
![](image/exercise1.png)

In [47]:
my_array = np.zeros((5,3))
my_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
for i in my_array:
    print(i+2)

[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]


### Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

**arange**

In [48]:
# create a range

x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [50]:
# create a range

x = np.arange(10, 20) # arguments: start, stop

x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
# create a range

x = np.arange(10, 20, 2) # arguments: start, stop, step

x

array([10, 12, 14, 16, 18])

In [ ]:
x = np.arange(-1, 1, 0.1)

x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

The number 9.00000000e-01 already is a floating point number.
It's written in scientific notation and is equivalent to 9 * 10**-1 or 0.9.

#### linspace

In [52]:
# using linspace, both end points ARE included
np.linspace(0, 10, 10) #Unlike arange that uses step, linspace uses the number of sample

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [53]:
np.linspace(0, 4, 10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

#### random data

In [9]:
from numpy import random

In [56]:
#uniform random numbers in [0,1]
random.rand(5,5)

array([[0.74142264, 0.00287873, 0.41870391, 0.60136251, 0.19125155],
       [0.42324721, 0.56917535, 0.14552886, 0.65265263, 0.07118441],
       [0.92031812, 0.31946327, 0.96840773, 0.32492249, 0.08795903],
       [0.81583197, 0.13275747, 0.32283983, 0.55422854, 0.24106127],
       [0.94275134, 0.25740052, 0.45810315, 0.76878232, 0.08615463]])

In [58]:
# standard normal distributed random numbers
x = random.randn(5,5)
x

array([[-1.37578842, -0.57137928,  0.34216708,  1.59291335,  0.10543515],
       [ 2.76549456,  0.35798113, -0.27127315, -0.41251831, -1.08873489],
       [-0.24574141, -1.42449962,  0.88308449, -0.60798628,  0.22274306],
       [-0.56319539, -0.06502403,  1.08849425,  0.7076125 , -0.30883209],
       [ 0.33208041,  0.93769773,  1.33041098,  0.27414637, -1.09041171]])

In [61]:
x.dtype

dtype('float64')

In [ ]:
x = np.ones(2, dtype = np.int64)
x

array([1, 1], dtype=int64)

In [66]:
random.randint(10)

6

In [73]:
random.randint(2, 10, size=4)

array([2, 3, 2, 6])

In [76]:
random.randint(2, 10, size=(4,2,2))

array([[[7, 3],
        [6, 9]],

       [[3, 2],
        [6, 6]],

       [[5, 7],
        [7, 7]],

       [[9, 5],
        [6, 5]]])

## Exercise 2

1. Generate a 1-D array containing 5 random integers from 0 to 100:

In [ ]:
random.randint(0,100, size=5)

array([83, 75, 78,  6, 31])

2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100

In [77]:
random.randint(1,100 , size=(3,5))

array([[70, 12, 42, 17, 58],
       [47, 81, 19, 88, 55],
       [96, 13, 61, 74,  2]])

3. Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.

In [78]:
x = np.linspace(1.5,5.5,30)

In [79]:
x

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])